[build]
  base = "/"
  publish = "dist"
  command = " npm install && npm run build"

[functions]
  directory = "/netlify/functions"


[context.deploy-preview]
  command = "npm install && npm run build "
